<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SupplyerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $supplyers = [
            [
                'name' => 'Abdul Karim',
                'company_name' => 'Karim Textile Traders',
                'code' => 'SUP-0001',
                'phone' => '01711000001',
                'phone_alt' => '01811000001',
                'email' => 'karim@karimtextile.com',
                'address' => 'Islampur Road, Old Dhaka',
                'city' => 'Dhaka',
                'postal_code' => '1100',
                'country' => 'Bangladesh',
                'trade_license' => 'TRD-DHK-10001',
                'tax_number' => 'TIN-100000001',
                'opening_balance' => 25000.00,
                'credit_limit' => 100000.00,
                'credit_days' => 30,
                'status' => 'active',
                'notes' => 'Regular textile and saree supplier.',
            ],
            [
                'name' => 'Mohammad Hasan',
                'company_name' => 'Hasan Fashion House',
                'code' => 'SUP-0002',
                'phone' => '01711000002',
                'phone_alt' => '01911000002',
                'email' => 'hasan@hasanfashion.com',
                'address' => 'Chawk Bazar, Lalbagh',
                'city' => 'Dhaka',
                'postal_code' => '1211',
                'country' => 'Bangladesh',
                'trade_license' => 'TRD-DHK-10002',
                'tax_number' => 'TIN-100000002',
                'opening_balance' => 15000.00,
                'credit_limit' => 75000.00,
                'credit_days' => 15,
                'status' => 'active',
                'notes' => 'Supplier of ladies clothing and three-piece.',
            ],
            [
                'name' => 'Sabbir Hossain',
                'company_name' => 'Sabbir Electronics',
                'code' => 'SUP-0003',
                'phone' => '01711000003',
                'phone_alt' => '01811000003',
                'email' => 'info@sabbirelectronics.com',
                'address' => 'Gulistan Shopping Complex',
                'city' => 'Dhaka',
                'postal_code' => '1000',
                'country' => 'Bangladesh',
                'trade_license' => 'TRD-DHK-10003',
                'tax_number' => 'TIN-100000003',
                'opening_balance' => 32000.00,
                'credit_limit' => 150000.00,
                'credit_days' => 45,
                'status' => 'active',
                'notes' => 'Computer accessories and electronics supplier.',
            ],
            [
                'name' => 'Rafiqul Islam',
                'company_name' => 'Rafiq Garments Supply',
                'code' => 'SUP-0004',
                'phone' => '01711000004',
                'phone_alt' => '01911000004',
                'email' => 'rafiq@rafiqgarments.com',
                'address' => 'Tongi Industrial Area',
                'city' => 'Gazipur',
                'postal_code' => '1710',
                'country' => 'Bangladesh',
                'trade_license' => 'TRD-GAZ-10004',
                'tax_number' => 'TIN-100000004',
                'opening_balance' => 18000.00,
                'credit_limit' => 120000.00,
                'credit_days' => 30,
                'status' => 'active',
                'notes' => 'Garments and ready-made clothing supplier.',
            ],
            [
                'name' => 'Nazmul Haque',
                'company_name' => 'Nazmul Wholesale Mart',
                'code' => 'SUP-0005',
                'phone' => '01711000005',
                'phone_alt' => '01811000005',
                'email' => 'nazmul@wholesalemart.com',
                'address' => 'Narayanganj Bazar',
                'city' => 'Narayanganj',
                'postal_code' => '1400',
                'country' => 'Bangladesh',
                'trade_license' => 'TRD-NAR-10005',
                'tax_number' => 'TIN-100000005',
                'opening_balance' => 12000.00,
                'credit_limit' => 80000.00,
                'credit_days' => 20,
                'status' => 'active',
                'notes' => 'General wholesale supplier.',
            ],
            [
                'name' => 'Imran Ahmed',
                'company_name' => 'Imran Fashion & Fabrics',
                'code' => 'SUP-0006',
                'phone' => '01711000006',
                'phone_alt' => '01911000006',
                'email' => 'imran@imranfabrics.com',
                'address' => 'Gawsia Market, Bhulta',
                'city' => 'Narayanganj',
                'postal_code' => '1460',
                'country' => 'Bangladesh',
                'trade_license' => 'TRD-NAR-10006',
                'tax_number' => 'TIN-100000006',
                'opening_balance' => 27500.00,
                'credit_limit' => 100000.00,
                'credit_days' => 30,
                'status' => 'active',
                'notes' => 'Fabric and fashion product supplier.',
            ],
            [
                'name' => 'Shahidul Alam',
                'company_name' => 'Shahid Trading Corporation',
                'code' => 'SUP-0007',
                'phone' => '01711000007',
                'phone_alt' => '01811000007',
                'email' => 'shahid@shahidtrading.com',
                'address' => 'Sadarghat, Old Dhaka',
                'city' => 'Dhaka',
                'postal_code' => '1100',
                'country' => 'Bangladesh',
                'trade_license' => 'TRD-DHK-10007',
                'tax_number' => 'TIN-100000007',
                'opening_balance' => 8500.00,
                'credit_limit' => 50000.00,
                'credit_days' => 15,
                'status' => 'active',
                'notes' => 'General merchandise supplier.',
            ],
            [
                'name' => 'Tanvir Rahman',
                'company_name' => 'Tanvir Lifestyle Products',
                'code' => 'SUP-0008',
                'phone' => '01711000008',
                'phone_alt' => '01911000008',
                'email' => 'tanvir@tanvirlifestyle.com',
                'address' => 'Uttara Sector 7',
                'city' => 'Dhaka',
                'postal_code' => '1230',
                'country' => 'Bangladesh',
                'trade_license' => 'TRD-DHK-10008',
                'tax_number' => 'TIN-100000008',
                'opening_balance' => 10000.00,
                'credit_limit' => 60000.00,
                'credit_days' => 30,
                'status' => 'active',
                'notes' => 'Lifestyle and consumer products supplier.',
            ],
            [
                'name' => 'Jahangir Kabir',
                'company_name' => 'Jahangir Home & Kitchen',
                'code' => 'SUP-0009',
                'phone' => '01711000009',
                'phone_alt' => '01811000009',
                'email' => 'jahangir@homekitchen.com',
                'address' => 'Mirpur 10 Market',
                'city' => 'Dhaka',
                'postal_code' => '1216',
                'country' => 'Bangladesh',
                'trade_license' => 'TRD-DHK-10009',
                'tax_number' => 'TIN-100000009',
                'opening_balance' => 19500.00,
                'credit_limit' => 90000.00,
                'credit_days' => 30,
                'status' => 'active',
                'notes' => 'Home appliances and kitchen products supplier.',
            ],
            [
                'name' => 'Mahfuzur Rahman',
                'company_name' => 'Mahfuz Enterprise',
                'code' => 'SUP-0010',
                'phone' => '01711000010',
                'phone_alt' => '01911000010',
                'email' => 'mahfuz@mahfuzenterprise.com',
                'address' => 'Konabari Industrial Area',
                'city' => 'Gazipur',
                'postal_code' => '1346',
                'country' => 'Bangladesh',
                'trade_license' => 'TRD-GAZ-10010',
                'tax_number' => 'TIN-100000010',
                'opening_balance' => 22000.00,
                'credit_limit' => 110000.00,
                'credit_days' => 45,
                'status' => 'active',
                'notes' => 'Wholesale supplier for retail businesses.',
            ],
        ];

        DB::table('supplyers')->insert($supplyers);
    }
}
